#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Simsip.LineRunner.Resource", IsApplication=true)]

namespace Simsip.LineRunner
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AuditApp.Android.Resource.Id.intercept_suggestion_comment = global::Simsip.LineRunner.Resource.Id.intercept_suggestion_comment;
			global::AuditApp.Android.Resource.Id.intercept_suggestion_done = global::Simsip.LineRunner.Resource.Id.intercept_suggestion_done;
			global::AuditApp.Android.Resource.Id.intercept_suggestion_header = global::Simsip.LineRunner.Resource.Id.intercept_suggestion_header;
			global::AuditApp.Android.Resource.Id.intercept_suggestion_id = global::Simsip.LineRunner.Resource.Id.intercept_suggestion_id;
			global::AuditApp.Android.Resource.Layout.intercept_suggestion_layout = global::Simsip.LineRunner.Resource.Layout.intercept_suggestion_layout;
			global::AuditApp.Android.Resource.String.library_name = global::Simsip.LineRunner.Resource.String.library_name;
			global::AuditApp.Android.Resource.Style.intercept_suggestion_background = global::Simsip.LineRunner.Resource.Style.intercept_suggestion_background;
			global::AuditApp.Android.Resource.Style.intercept_suggestion_commentstyle = global::Simsip.LineRunner.Resource.Style.intercept_suggestion_commentstyle;
			global::AuditApp.Android.Resource.Style.intercept_suggestion_donebuttonstyle = global::Simsip.LineRunner.Resource.Style.intercept_suggestion_donebuttonstyle;
			global::AuditApp.Android.Resource.Style.intercept_suggestion_headerstyle = global::Simsip.LineRunner.Resource.Style.intercept_suggestion_headerstyle;
			global::AuditApp.Android.Resource.Style.intercept_suggestion_idstyle = global::Simsip.LineRunner.Resource.Style.intercept_suggestion_idstyle;
			global::SQLite.Resource.String.ApplicationName = global::Simsip.LineRunner.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Simsip.LineRunner.Resource.String.Hello;
			global::Xamarin.InAppBilling.Resource.String.library_name = global::Simsip.LineRunner.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int intercept_suggestion_comment = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int intercept_suggestion_done = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int intercept_suggestion_header = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int intercept_suggestion_id = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int webview = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int intercept_suggestion_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int View_OAuth = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040076
			public const int AchievementsColumnDate = 2130968694;
			
			// aapt resource value: 0x7f040078
			public const int AchievementsColumnScore = 2130968696;
			
			// aapt resource value: 0x7f040077
			public const int AchievementsColumnTime = 2130968695;
			
			// aapt resource value: 0x7f040016
			public const int AchievementsLeaderboards = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int AchievementsTopScoresFor = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int AdminKillsOff = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int AdminKillsOn = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int AdminParticlesOff = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int AdminParticlesOn = 2130968603;
			
			// aapt resource value: 0x7f04004d
			public const int AdminStartLine = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int AdminStartLineDescription = 2130968654;
			
			// aapt resource value: 0x7f04001c
			public const int AdminStartPage = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int AdminStartPageDescription = 2130968605;
			
			// aapt resource value: 0x7f04006e
			public const int AdminUpgradesOff = 2130968686;
			
			// aapt resource value: 0x7f04006f
			public const int AdminUpgradesOn = 2130968687;
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040030
			public const int CommonAdmin = 2130968624;
			
			// aapt resource value: 0x7f040082
			public const int CommonBack = 2130968706;
			
			// aapt resource value: 0x7f04001e
			public const int CommonCancel = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int CommonDelete = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int CommonError = 2130968608;
			
			// aapt resource value: 0x7f04003c
			public const int CommonLater = 2130968636;
			
			// aapt resource value: 0x7f040083
			public const int CommonNext = 2130968707;
			
			// aapt resource value: 0x7f040021
			public const int CommonNo = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int CommonOK = 2130968610;
			
			// aapt resource value: 0x7f040044
			public const int CommonPage = 2130968644;
			
			// aapt resource value: 0x7f040084
			public const int CommonPrevious = 2130968708;
			
			// aapt resource value: 0x7f040050
			public const int CommonReset = 2130968656;
			
			// aapt resource value: 0x7f040005
			public const int CommonVersion = 2130968581;
			
			// aapt resource value: 0x7f040023
			public const int CommonYes = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int CreditsCreatedBy = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int CreditsCreatedBySimsip = 2130968613;
			
			// aapt resource value: 0x7f04003f
			public const int CreditsTitle = 2130968639;
			
			// aapt resource value: 0x7f040026
			public const int FinishNewHighScore = 2130968614;
			
			// aapt resource value: 0x7f04007b
			public const int FinishWinner = 2130968699;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int HelpHelpDescription = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int HelpHowToPlayDescription1 = 2130968583;
			
			// aapt resource value: 0x7f040059
			public const int HelpHud = 2130968665;
			
			// aapt resource value: 0x7f040051
			public const int HelpIncreaseDecrease = 2130968657;
			
			// aapt resource value: 0x7f04005a
			public const int HelpLeaderboards = 2130968666;
			
			// aapt resource value: 0x7f04004f
			public const int HelpLicense = 2130968655;
			
			// aapt resource value: 0x7f040008
			public const int HelpLines = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int HelpOptions = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int HelpOptionsDescription = 2130968586;
			
			// aapt resource value: 0x7f040052
			public const int HelpOrbit = 2130968658;
			
			// aapt resource value: 0x7f04000b
			public const int HelpPads = 2130968587;
			
			// aapt resource value: 0x7f040053
			public const int HelpPauseResume = 2130968659;
			
			// aapt resource value: 0x7f04000c
			public const int HelpRatingsDescription = 2130968588;
			
			// aapt resource value: 0x7f040054
			public const int HelpRotate = 2130968660;
			
			// aapt resource value: 0x7f040055
			public const int HelpScroll = 2130968661;
			
			// aapt resource value: 0x7f04005b
			public const int HelpSound = 2130968667;
			
			// aapt resource value: 0x7f04000d
			public const int HelpStartDescription = 2130968589;
			
			// aapt resource value: 0x7f04007a
			public const int HelpSupport = 2130968698;
			
			// aapt resource value: 0x7f04000e
			public const int HelpTitle = 2130968590;
			
			// aapt resource value: 0x7f040060
			public const int HelpUpgrades = 2130968672;
			
			// aapt resource value: 0x7f040061
			public const int HelpUpgradesPractice = 2130968673;
			
			// aapt resource value: 0x7f040062
			public const int HelpUpgradesPracticeDesc1 = 2130968674;
			
			// aapt resource value: 0x7f040063
			public const int HelpUpgradesPracticeDesc2 = 2130968675;
			
			// aapt resource value: 0x7f040085
			public const int HelpZoomInOut = 2130968709;
			
			// aapt resource value: 0x7f040047
			public const int HudCannotGoSlowerThan = 2130968647;
			
			// aapt resource value: 0x7f040040
			public const int HudHelp = 2130968640;
			
			// aapt resource value: 0x7f040079
			public const int HudHigh = 2130968697;
			
			// aapt resource value: 0x7f04004c
			public const int HudHome = 2130968652;
			
			// aapt resource value: 0x7f040049
			public const int HudJoystick = 2130968649;
			
			// aapt resource value: 0x7f040041
			public const int HudOptions = 2130968641;
			
			// aapt resource value: 0x7f040056
			public const int HudOrbit = 2130968662;
			
			// aapt resource value: 0x7f040027
			public const int HudPageLine = 2130968615;
			
			// aapt resource value: 0x7f040045
			public const int HudPause = 2130968645;
			
			// aapt resource value: 0x7f040048
			public const int HudPaused = 2130968648;
			
			// aapt resource value: 0x7f040028
			public const int HudResume = 2130968616;
			
			// aapt resource value: 0x7f040057
			public const int HudRotate = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int HudScroll = 2130968664;
			
			// aapt resource value: 0x7f040046
			public const int HudSpeed = 2130968646;
			
			// aapt resource value: 0x7f040086
			public const int HudSpeedDefault = 2130968710;
			
			// aapt resource value: 0x7f04004b
			public const int HudTime = 2130968651;
			
			// aapt resource value: 0x7f04004a
			public const int HudTrackball = 2130968650;
			
			// aapt resource value: 0x7f040029
			public const int LinesSwitchingLines = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int LoginPassword = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int LoginPasswordDescription = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int LoginUserName = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int LoginUserNameDescription = 2130968621;
			
			// aapt resource value: 0x7f04007c
			public const int MessageBoxMovingToPage = 2130968700;
			
			// aapt resource value: 0x7f04007d
			public const int MessageBoxMovingToPage2 = 2130968701;
			
			// aapt resource value: 0x7f04007e
			public const int MessageBoxMovingToPage3 = 2130968702;
			
			// aapt resource value: 0x7f04007f
			public const int MessageBoxMovingToPage4 = 2130968703;
			
			// aapt resource value: 0x7f040080
			public const int MessageBoxMovingToPage5 = 2130968704;
			
			// aapt resource value: 0x7f040081
			public const int MessageBoxMovingToPage6 = 2130968705;
			
			// aapt resource value: 0x7f04000f
			public const int OptionsCredits = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int OptionsLeaderboards = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int OptionsLines = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int OptionsPads = 2130968594;
			
			// aapt resource value: 0x7f040070
			public const int OptionsPractice = 2130968688;
			
			// aapt resource value: 0x7f040068
			public const int OptionsPracticeKillsOff = 2130968680;
			
			// aapt resource value: 0x7f040069
			public const int OptionsPracticeKillsOn = 2130968681;
			
			// aapt resource value: 0x7f04006a
			public const int OptionsPracticeStartLine = 2130968682;
			
			// aapt resource value: 0x7f04006b
			public const int OptionsPracticeStartPage = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int OptionsPracticeSwitchingLine = 2130968684;
			
			// aapt resource value: 0x7f04006d
			public const int OptionsPracticeSwitchingPage = 2130968685;
			
			// aapt resource value: 0x7f040013
			public const int OptionsSoundOff = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int OptionsSoundOn = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int OptionsTitle = 2130968597;
			
			// aapt resource value: 0x7f04002e
			public const int PadsSwitchingPads = 2130968622;
			
			// aapt resource value: 0x7f04003d
			public const int RatingsDescription = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int RatingsRateUs = 2130968638;
			
			// aapt resource value: 0x7f040003
			public const int ResourceFlowDirection = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ResourceLanguage = 2130968580;
			
			// aapt resource value: 0x7f04002f
			public const int ResourcePacksSwitchingResourcePacks = 2130968623;
			
			// aapt resource value: 0x7f040042
			public const int StartPlay = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int StartRate = 2130968643;
			
			// aapt resource value: 0x7f040064
			public const int UpgradesBuy = 2130968676;
			
			// aapt resource value: 0x7f04005d
			public const int UpgradesPractice = 2130968669;
			
			// aapt resource value: 0x7f04005e
			public const int UpgradesPracticeDesc1 = 2130968670;
			
			// aapt resource value: 0x7f04005f
			public const int UpgradesPracticeDesc2 = 2130968671;
			
			// aapt resource value: 0x7f040071
			public const int UpgradesPracticeDesc3 = 2130968689;
			
			// aapt resource value: 0x7f040065
			public const int UpgradesPrice = 2130968677;
			
			// aapt resource value: 0x7f040072
			public const int UpgradesPurchaseError = 2130968690;
			
			// aapt resource value: 0x7f040073
			public const int UpgradesPurchaseStatus = 2130968691;
			
			// aapt resource value: 0x7f040066
			public const int UpgradesPurchasedOn = 2130968678;
			
			// aapt resource value: 0x7f040067
			public const int UpgradesRestore = 2130968679;
			
			// aapt resource value: 0x7f040074
			public const int UpgradesRestoreError = 2130968692;
			
			// aapt resource value: 0x7f040075
			public const int UpgradesRestoreStatus = 2130968693;
			
			// aapt resource value: 0x7f04005c
			public const int UpgradesTitle = 2130968668;
			
			// aapt resource value: 0x7f040031
			public const int WorldsDefault = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int WorldsErrorCannotUseName = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int WorldsErrorWorldActive = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int WorldsErrorWorldAlreadyExists = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int WorldsGenerateNew = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int WorldsSaveWorldAs = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int WorldsSaveWorldAsDescription = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int WorldsSelectNewWorld = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int WorldsSwitchingWorlds = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int WorldsUseThisWorld = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int WorldsWorlds = 2130968635;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050005
			public const int Theme_Splash = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int intercept_suggestion_background = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int intercept_suggestion_commentstyle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int intercept_suggestion_donebuttonstyle = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int intercept_suggestion_headerstyle = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int intercept_suggestion_idstyle = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
