//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simsip.LineRunner.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simsip.LineRunner.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string AchievementsColumnDate {
            get {
                return ResourceManager.GetString("AchievementsColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score.
        /// </summary>
        public static string AchievementsColumnScore {
            get {
                return ResourceManager.GetString("AchievementsColumnScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string AchievementsColumnTime {
            get {
                return ResourceManager.GetString("AchievementsColumnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaderboards.
        /// </summary>
        public static string AchievementsLeaderboards {
            get {
                return ResourceManager.GetString("AchievementsLeaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to top scores.
        /// </summary>
        public static string AchievementsTopScoresFor {
            get {
                return ResourceManager.GetString("AchievementsTopScoresFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string CommonAdmin {
            get {
                return ResourceManager.GetString("CommonAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string CommonBack {
            get {
                return ResourceManager.GetString("CommonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CommonCancel {
            get {
                return ResourceManager.GetString("CommonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string CommonDelete {
            get {
                return ResourceManager.GetString("CommonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string CommonError {
            get {
                return ResourceManager.GetString("CommonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to later.
        /// </summary>
        public static string CommonLater {
            get {
                return ResourceManager.GetString("CommonLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string CommonNext {
            get {
                return ResourceManager.GetString("CommonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string CommonNo {
            get {
                return ResourceManager.GetString("CommonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string CommonOK {
            get {
                return ResourceManager.GetString("CommonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page.
        /// </summary>
        public static string CommonPage {
            get {
                return ResourceManager.GetString("CommonPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string CommonPrevious {
            get {
                return ResourceManager.GetString("CommonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double tap trackball to reset view.
        /// </summary>
        public static string CommonReset {
            get {
                return ResourceManager.GetString("CommonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string CommonVersion {
            get {
                return ResourceManager.GetString("CommonVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string CommonYes {
            get {
                return ResourceManager.GetString("CommonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to development.
        /// </summary>
        public static string CreditsCreatedBy {
            get {
                return ResourceManager.GetString("CreditsCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simsip.
        /// </summary>
        public static string CreditsCreatedBySimsip {
            get {
                return ResourceManager.GetString("CreditsCreatedBySimsip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits.
        /// </summary>
        public static string CreditsTitle {
            get {
                return ResourceManager.GetString("CreditsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new high score.
        /// </summary>
        public static string FinishNewHighScore {
            get {
                return ResourceManager.GetString("FinishNewHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winner!.
        /// </summary>
        public static string FinishWinner {
            get {
                return ResourceManager.GetString("FinishWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap to avoid lines and obstacles.
        /// </summary>
        public static string HelpHowToPlayDescription1 {
            get {
                return ResourceManager.GetString("HelpHowToPlayDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hud.
        /// </summary>
        public static string HelpHud {
            get {
                return ResourceManager.GetString("HelpHud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to increase or decrease speed.
        /// </summary>
        public static string HelpIncreaseDecrease {
            get {
                return ResourceManager.GetString("HelpIncreaseDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see your top scores.
        /// </summary>
        public static string HelpLeaderboards {
            get {
                return ResourceManager.GetString("HelpLeaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license.
        /// </summary>
        public static string HelpLicense {
            get {
                return ResourceManager.GetString("HelpLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change the line for the pad.
        /// </summary>
        public static string HelpLines {
            get {
                return ResourceManager.GetString("HelpLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string HelpOptions {
            get {
                return ResourceManager.GetString("HelpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drag from trackball to orbit view.
        /// </summary>
        public static string HelpOrbit {
            get {
                return ResourceManager.GetString("HelpOrbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change the pad you play on.
        /// </summary>
        public static string HelpPads {
            get {
                return ResourceManager.GetString("HelpPads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause or resume the game.
        /// </summary>
        public static string HelpPauseResume {
            get {
                return ResourceManager.GetString("HelpPauseResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate us.
        /// </summary>
        public static string HelpRatingsDescription {
            get {
                return ResourceManager.GetString("HelpRatingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drag from middle to rotate view.
        /// </summary>
        public static string HelpRotate {
            get {
                return ResourceManager.GetString("HelpRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap or hold to scroll view.
        /// </summary>
        public static string HelpScroll {
            get {
                return ResourceManager.GetString("HelpScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn sound off and on.
        /// </summary>
        public static string HelpSound {
            get {
                return ResourceManager.GetString("HelpSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play game.
        /// </summary>
        public static string HelpStartDescription {
            get {
                return ResourceManager.GetString("HelpStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        public static string HelpSupport {
            get {
                return ResourceManager.GetString("HelpSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgrades.
        /// </summary>
        public static string HelpUpgrades {
            get {
                return ResourceManager.GetString("HelpUpgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to practice mode.
        /// </summary>
        public static string HelpUpgradesPractice {
            get {
                return ResourceManager.GetString("HelpUpgradesPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jump to any page and line.
        /// </summary>
        public static string HelpUpgradesPracticeDesc1 {
            get {
                return ResourceManager.GetString("HelpUpgradesPracticeDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn kills off.
        /// </summary>
        public static string HelpUpgradesPracticeDesc2 {
            get {
                return ResourceManager.GetString("HelpUpgradesPracticeDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom in or out.
        /// </summary>
        public static string HelpZoomInOut {
            get {
                return ResourceManager.GetString("HelpZoomInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot go slower than.
        /// </summary>
        public static string HudCannotGoSlowerThan {
            get {
                return ResourceManager.GetString("HudCannotGoSlowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HudHelp {
            get {
                return ResourceManager.GetString("HudHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        public static string HudHigh {
            get {
                return ResourceManager.GetString("HudHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string HudHome {
            get {
                return ResourceManager.GetString("HudHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joystick.
        /// </summary>
        public static string HudJoystick {
            get {
                return ResourceManager.GetString("HudJoystick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string HudOptions {
            get {
                return ResourceManager.GetString("HudOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page/line.
        /// </summary>
        public static string HudPageLine {
            get {
                return ResourceManager.GetString("HudPageLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string HudPause {
            get {
                return ResourceManager.GetString("HudPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        public static string HudPaused {
            get {
                return ResourceManager.GetString("HudPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resume.
        /// </summary>
        public static string HudResume {
            get {
                return ResourceManager.GetString("HudResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speed.
        /// </summary>
        public static string HudSpeed {
            get {
                return ResourceManager.GetString("HudSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (default).
        /// </summary>
        public static string HudSpeedDefault {
            get {
                return ResourceManager.GetString("HudSpeedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string HudTime {
            get {
                return ResourceManager.GetString("HudTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trackball.
        /// </summary>
        public static string HudTrackball {
            get {
                return ResourceManager.GetString("HudTrackball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom.
        /// </summary>
        public static string HudZoom {
            get {
                return ResourceManager.GetString("HudZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blue.
        /// </summary>
        public static string LinesBlue {
            get {
                return ResourceManager.GetString("LinesBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark green.
        /// </summary>
        public static string LinesDarkGreen {
            get {
                return ResourceManager.GetString("LinesDarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark orange.
        /// </summary>
        public static string LinesDarkOrange {
            get {
                return ResourceManager.GetString("LinesDarkOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to green.
        /// </summary>
        public static string LinesGreen {
            get {
                return ResourceManager.GetString("LinesGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light blue.
        /// </summary>
        public static string LinesLightBlue {
            get {
                return ResourceManager.GetString("LinesLightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light green.
        /// </summary>
        public static string LinesLightGreen {
            get {
                return ResourceManager.GetString("LinesLightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light orange.
        /// </summary>
        public static string LinesLightOrange {
            get {
                return ResourceManager.GetString("LinesLightOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orange.
        /// </summary>
        public static string LinesOrange {
            get {
                return ResourceManager.GetString("LinesOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        public static string LinesRed {
            get {
                return ResourceManager.GetString("LinesRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switching lines.
        /// </summary>
        public static string LinesSwitchingLines {
            get {
                return ResourceManager.GetString("LinesSwitchingLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moving to page.
        /// </summary>
        public static string MessageBoxMovingToPage {
            get {
                return ResourceManager.GetString("MessageBoxMovingToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you&apos;re awesome!.
        /// </summary>
        public static string MessageBoxMovingToPage2 {
            get {
                return ResourceManager.GetString("MessageBoxMovingToPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boom!.
        /// </summary>
        public static string MessageBoxMovingToPage3 {
            get {
                return ResourceManager.GetString("MessageBoxMovingToPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sweetness!.
        /// </summary>
        public static string MessageBoxMovingToPage4 {
            get {
                return ResourceManager.GetString("MessageBoxMovingToPage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fire!.
        /// </summary>
        public static string MessageBoxMovingToPage5 {
            get {
                return ResourceManager.GetString("MessageBoxMovingToPage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last page!.
        /// </summary>
        public static string MessageBoxMovingToPage6 {
            get {
                return ResourceManager.GetString("MessageBoxMovingToPage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credits.
        /// </summary>
        public static string OptionsCredits {
            get {
                return ResourceManager.GetString("OptionsCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaderboards.
        /// </summary>
        public static string OptionsLeaderboards {
            get {
                return ResourceManager.GetString("OptionsLeaderboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lines.
        /// </summary>
        public static string OptionsLines {
            get {
                return ResourceManager.GetString("OptionsLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pads.
        /// </summary>
        public static string OptionsPads {
            get {
                return ResourceManager.GetString("OptionsPads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to practice mode.
        /// </summary>
        public static string OptionsPractice {
            get {
                return ResourceManager.GetString("OptionsPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kills off.
        /// </summary>
        public static string OptionsPracticeKillsOff {
            get {
                return ResourceManager.GetString("OptionsPracticeKillsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kills on.
        /// </summary>
        public static string OptionsPracticeKillsOn {
            get {
                return ResourceManager.GetString("OptionsPracticeKillsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting line.
        /// </summary>
        public static string OptionsPracticeStartLine {
            get {
                return ResourceManager.GetString("OptionsPracticeStartLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting page.
        /// </summary>
        public static string OptionsPracticeStartPage {
            get {
                return ResourceManager.GetString("OptionsPracticeStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switching line to.
        /// </summary>
        public static string OptionsPracticeSwitchingLine {
            get {
                return ResourceManager.GetString("OptionsPracticeSwitchingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switching page to.
        /// </summary>
        public static string OptionsPracticeSwitchingPage {
            get {
                return ResourceManager.GetString("OptionsPracticeSwitchingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound off.
        /// </summary>
        public static string OptionsSoundOff {
            get {
                return ResourceManager.GetString("OptionsSoundOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound on.
        /// </summary>
        public static string OptionsSoundOn {
            get {
                return ResourceManager.GetString("OptionsSoundOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to options.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switching pads.
        /// </summary>
        public static string PadsSwitchingPads {
            get {
                return ResourceManager.GetString("PadsSwitchingPads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white.
        /// </summary>
        public static string PadsWhite {
            get {
                return ResourceManager.GetString("PadsWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yellow.
        /// </summary>
        public static string PadsYellow {
            get {
                return ResourceManager.GetString("PadsYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D.
        /// </summary>
        public static string Start3D {
            get {
                return ResourceManager.GetString("Start3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string StartLine {
            get {
                return ResourceManager.GetString("StartLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string StartPlay {
            get {
                return ResourceManager.GetString("StartPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate.
        /// </summary>
        public static string StartRate {
            get {
                return ResourceManager.GetString("StartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runner.
        /// </summary>
        public static string StartRunner {
            get {
                return ResourceManager.GetString("StartRunner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        public static string UpgradesBuy {
            get {
                return ResourceManager.GetString("UpgradesBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to practice mode.
        /// </summary>
        public static string UpgradesPractice {
            get {
                return ResourceManager.GetString("UpgradesPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jump to any page and line.
        /// </summary>
        public static string UpgradesPracticeDesc1 {
            get {
                return ResourceManager.GetString("UpgradesPracticeDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn kills off.
        /// </summary>
        public static string UpgradesPracticeDesc2 {
            get {
                return ResourceManager.GetString("UpgradesPracticeDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tap options for practice mode.
        /// </summary>
        public static string UpgradesPracticeDesc3 {
            get {
                return ResourceManager.GetString("UpgradesPracticeDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        public static string UpgradesPrice {
            get {
                return ResourceManager.GetString("UpgradesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchased on.
        /// </summary>
        public static string UpgradesPurchasedOn {
            get {
                return ResourceManager.GetString("UpgradesPurchasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error purchasing upgrade.
        /// </summary>
        public static string UpgradesPurchaseError {
            get {
                return ResourceManager.GetString("UpgradesPurchaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchasing upgrade.
        /// </summary>
        public static string UpgradesPurchaseStatus {
            get {
                return ResourceManager.GetString("UpgradesPurchaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore.
        /// </summary>
        public static string UpgradesRestore {
            get {
                return ResourceManager.GetString("UpgradesRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error restoring upgrade.
        /// </summary>
        public static string UpgradesRestoreError {
            get {
                return ResourceManager.GetString("UpgradesRestoreError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restoring upgrade.
        /// </summary>
        public static string UpgradesRestoreStatus {
            get {
                return ResourceManager.GetString("UpgradesRestoreStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgrades.
        /// </summary>
        public static string UpgradesTitle {
            get {
                return ResourceManager.GetString("UpgradesTitle", resourceCulture);
            }
        }
    }
}
